patch 0.1.55: New mcusim API for Lua-based models.
- New firmware test option is available to let simulator not to wait for any
  external events or a debugger to continue simulation;
- mcusim doesn't start a simulation if it cannot load all required Lua
  models;
- Simulation return code is used an exit code of mcusim;
- New AVR MCU state AVR_MSIM_TESTFAIL added to stop simulation because
  of a failed test (this is specifically useful for test Lua scripts);
- MCU is forced to finish multicycle instruction despite the current
  state;
- New mcusim API for Lua-based models implemented (including new
  functions, MCU I/O registers, MCU states available inside Lua script,
  and a model configuration function support).

Signed-off-by: Dmitry Salychev <darkness.bsd@gmail.com>

diff --git a/scripts/mcusim-config b/scripts/mcusim-config
--- a/scripts/mcusim-config
+++ b/scripts/mcusim-config
@@ -37,7 +37,7 @@
 # Check programs available within operating system
 MSIM=$(which mcusim)
 if [ $? -ne 0 ]; then
-	printf "[!] mcusim-avr not installed. Unable to create a "
+	printf "[!] mcusim not installed. Unable to create a "
 	printf "configuration script.\n" >&2
 	exit 1
 fi
@@ -54,6 +54,7 @@ MCU_FAMILY_DEFAULT="avr"
 CFG_DIR_DEFAULT="$HOME"
 MSIM_VERSION=`$MSIM --short-version`
 MCU_FAMILY=$MCU_FAMILY_DEFAULT
+FIRMWARE_TEST="n"
 # -----------END Default values for script-wide variables ---------------------
 
 
@@ -155,40 +156,59 @@ while [ $FMW_PROVIDED -eq 0 ]; do
 done
 # ------------END Firmware/Bootloader -----------------------------------------
 
+printf "Do you want to perform additional configuration? [y/N]: "
+read ADDITIONAL_CONF
+if [ "$ADDITIONAL_CONF" == "y" ] && [ "$ADDITIONAL_CONF" != "Y" ] ; then
+	# ---------------- Model configuration --------------------------------
+	# Note: These fuse bytes and lock bits are for AVR only. I'll have to
+	#       modify this part in order to support other models and provide
+	#       additional parameters.
+	printf "Frequency (in Hz, leave empty for default): "
+	read MCU_FREQ
+	printf "Lock bits byte (leave empty for default): "
+	read LOCK_BYTE
+	printf "Extended fuse byte (leave empty for default): "
+	read EXT_FUSE
+	printf "High fuse byte (leave empty for default): "
+	read HIGH_FUSE
+	printf "Low fuse byte (leave empty for default): "
+	read LOW_FUSE
+	# -------------END Model configuration --------------------------------
 
-# ---------------- Model configuration ----------------------------------------
-# Note: These fuse bytes and lock bits are for AVR only. I'll have to modify
-#       this part in order to support other models and provide additional
-#       parameters.
-printf "Lock bits byte (Leave empty for default): "
-read LOCK_BYTE
-printf "Extended fuse byte (Leave empty for default): "
-read EXT_FUSE
-printf "High fuse byte (Leave empty for default): "
-read HIGH_FUSE
-printf "Low fuse byte (Leave empty for default): "
-read LOW_FUSE
-# -------------END Model configuration ----------------------------------------
 
+	# ---------------- Simulator configuration ----------------------------
+	printf "Do you want to set up a firmware test? [y/N]: "
+	read FIRMWARE_TEST
+	if [ "$FIRMWARE_TEST" != "y" ] && [ "$FIRMWARE_TEST" != "Y" ] ; then
+		FIRMWARE_TEST="no"
+	else
+		FIRMWARE_TEST="yes"
+	fi
+	# -------------END Simulator configuration ----------------------------
+fi
 
 # -------------- Verify a configuration ---------------------------------------
 echo "Please, verify this configuration:"
 echo ""
 echo "    Configuration: $CFG_DIR/$CFG_NAME"
 echo "    Model: $MCU_MODEL"
+echo "    Frequency: $MCU_FREQ Hz"
 echo "    Lock bits: $LOCK_BYTE"
-echo "    Fuses: EXT=$EXT_FUSE, HIGH=$HIGH_FUSE, LOW=$LOW_FUSE"
+echo "    Fuses: EXT=$EXT_FUSE,"
+echo "           HIGH=$HIGH_FUSE,"
+echo "           LOW=$LOW_FUSE"
+echo "    Firmware test: $FIRMWARE_TEST"
 echo ""
 printf "Is it correct? [y/N] "
 read VALID_CFG
 if [ "$VALID_CFG" != "y" ] && [ "$VALID_CFG" != "Y" ] ; then
-	echo "Configuration is incorrect, script won't be created."
+	printf "Configuration is incorrect, script won't be created. "
+	printf "Thanks!\n\n"
 	exit 0
 else
 	printf "Configuration is correct, script will be created "
-	printf "at $CFG_DIR/$CFG_NAME."
+	printf "at $CFG_DIR/$CFG_NAME. Thanks!\n\n"
 fi
-printf " Thanks!\n\n"
 # -----------END Verify a configuration ---------------------------------------
 
 
@@ -238,15 +258,29 @@ echo "#" >> $CFG_DIR/$CFG_NAME
 echo "" >> $CFG_DIR/$CFG_NAME
 
 echo "# Append models to the list in order to load them during simulation." >> $CFG_DIR/$CFG_NAME
-echo "MODELS=\"./dht11.lua\n\"" >> $CFG_DIR/$CFG_NAME
-echo "MODELS=\"\$MODELS./io.lua\n\"" >> $CFG_DIR/$CFG_NAME
+echo "#MODELS=\"\$MODELS./dht11.lua\n\"" >> $CFG_DIR/$CFG_NAME
+echo "#MODELS=\"\$MODELS./io.lua\n\"" >> $CFG_DIR/$CFG_NAME
 echo "" >> $CFG_DIR/$CFG_NAME
 echo "# File to keep list of the models" >> $CFG_DIR/$CFG_NAME
-echo "MDL_LIST=\"./.$CFG_NAME.mdl\"" >> $CFG_DIR/$CFG_NAME
-echo "printf \$MODELS > \$MDL_LIST" >> $CFG_DIR/$CFG_NAME
+echo "MDL_LIST=\"./$CFG_NAME.mod.txt\"" >> $CFG_DIR/$CFG_NAME
+echo "rm -f ./$CFG_NAME.mod.txt" >> $CFG_DIR/$CFG_NAME
+echo "echo \"# DO NOT MODIFY IT MANUALLY! FILE WILL BE OVERWRITTEN!\" > \$MDL_LIST" >> $CFG_DIR/$CFG_NAME
+echo "if [ ! -z \"\$MODELS\" ]; then" >> $CFG_DIR/$CFG_NAME
+echo "        printf \$MODELS >> \$MDL_LIST" >> $CFG_DIR/$CFG_NAME
+echo "fi" >> $CFG_DIR/$CFG_NAME
 echo "" >> $CFG_DIR/$CFG_NAME
 
 MSIM_CMD="$MSIM -p $MCU_MODEL -r \$MDL_LIST"
+
+# Set frequency option
+if [ ! -z "$MCU_FREQ" ]; then
+	MSIM_CMD="$MSIM_CMD -f $MCU_FREQ"
+fi
+
+# Set firmware test option
+if [ "$FIRMWARE_TEST" == "yes" ]; then
+	MSIM_CMD="$MSIM_CMD --firmware-test"
+fi
 
 if [ -f "$FMW_PATH" ]; then
 	MSIM_CMD="$MSIM_CMD -U flash:w:$FMW_PATH"
@@ -266,6 +300,7 @@ fi
 if [ ! -z "$LOW_FUSE" ]; then
 	MSIM_CMD="$MSIM_CMD -U lfuse:w:$LOW_FUSE:h"
 fi
-echo "$MSIM_CMD" >> $CFG_DIR/$CFG_NAME
-echo "rm \$MDL_LIST" >> $CFG_DIR/$CFG_NAME
+echo "$MSIM_CMD; rc=\$?" >> $CFG_DIR/$CFG_NAME
+echo "rm -f ./$CFG_NAME.mod.txt" >> $CFG_DIR/$CFG_NAME
+echo "exit \$rc" >> $CFG_DIR/$CFG_NAME
 # --------------END Generate script -------------------------------------------
